<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="OrangeHRMSuite" duration-ms="37168" started-at="2020-07-26T12:41:46Z" finished-at="2020-07-26T12:42:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="37168" started-at="2020-07-26T12:41:46Z" finished-at="2020-07-26T12:42:23Z">
      <class name="testCases.Login_DataDriven">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="setup" is-config="true" duration-ms="9549" started-at="2020-07-26T12:41:47Z" finished-at="2020-07-26T12:41:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginWithDifferentSetOfData(java.lang.String, java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="loginWithDifferentSetOfData" duration-ms="4872" started-at="2020-07-26T12:41:56Z" data-provider="LoginData" finished-at="2020-07-26T12:42:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithDifferentSetOfData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="tearDown" is-config="true" duration-ms="608" started-at="2020-07-26T12:42:01Z" finished-at="2020-07-26T12:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="setup" is-config="true" duration-ms="8190" started-at="2020-07-26T12:42:02Z" finished-at="2020-07-26T12:42:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginWithDifferentSetOfData(java.lang.String, java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="loginWithDifferentSetOfData" duration-ms="1846" started-at="2020-07-26T12:42:10Z" data-provider="LoginData" finished-at="2020-07-26T12:42:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dfdfdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testCases.Login_DataDriven.loginWithDifferentSetOfData(Login_DataDriven.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithDifferentSetOfData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="tearDown" is-config="true" duration-ms="610" started-at="2020-07-26T12:42:12Z" finished-at="2020-07-26T12:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="setup" is-config="true" duration-ms="8747" started-at="2020-07-26T12:42:12Z" finished-at="2020-07-26T12:42:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginWithDifferentSetOfData(java.lang.String, java.lang.String)[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="loginWithDifferentSetOfData" duration-ms="1430" started-at="2020-07-26T12:42:21Z" data-provider="LoginData" finished-at="2020-07-26T12:42:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[fdfdfd]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[fgfgffg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testCases.Login_DataDriven.loginWithDifferentSetOfData(Login_DataDriven.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithDifferentSetOfData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.Login_DataDriven@5442a311]" name="tearDown" is-config="true" duration-ms="605" started-at="2020-07-26T12:42:23Z" finished-at="2020-07-26T12:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.Login_DataDriven -->
    </test> <!-- Test -->
  </suite> <!-- OrangeHRMSuite -->
</testng-results>
